###
POST http://localhost:5032/api/Files/import
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="file"; filename="1.ofx"
Content-Type: application/octet-stream

< ./real.ofx
--MyBoundary
Content-Disposition: form-data; name="fileName"

тестовый_файл2
--MyBoundary--